# Name of your site (displayed in the header)
name: Jo's Blog

# Name of the author
author: Jo
# Short bio or description (displayed in the header)
description: A Taiwanese web developer lives in Kyoto, Japan.
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/jo.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: kobanae+github@gmail.com
  facebook:
  flickr:
  github: Jo-Minken
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter: 
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
